### ISSUE TITLE
How is it possible to run this app?

### ISSUE THREAD

**Issue by andresfelipe66** [karthik07m/coredova-Sample-Ecommerce-app#2]
Hello. The app sounds great… But its no clear how run in Cordova. Do you have a manual o something like this?
Could you improve the README file?

Thank you!!

**Comment by karthik07m** [comment]
Check out this video to know how to set up Cordova and run the app:
https://channel9.msdn.com/Series/Visual-Studio-Tools-for-Apache-Cordova/Building-Apache-Cordova-Apps-with-Visual-Studio
